<script setup lang="ts">
import { computed, ref } from 'vue'; import AppHeader from './components/AppHeader.vue'; import WorkflowSteps from './components/WorkflowSteps.vue'; import TemplateManager from './components/TemplateManager.vue'; import PhotoCropper from './components/PhotoCropper.vue'; import A4Page from './components/A4Page.vue'; import { activePhoto, importFiles, removePhoto, state } from './store/photoStore'; import { packPhotos } from './utils/packing'
const step = ref(1), dragging = ref(false), input = ref<HTMLInputElement>(), loading = ref(false)
const pages = computed(() => packPhotos(state.photos, state.templates, state.margin, state.gap))
async function receive(files: FileList | null){ if(!files?.length)return; loading.value=true; try{await importFiles([...files]); if(state.photos.length) step.value=2}finally{loading.value=false; if(input.value)input.value.value=''} }
function drop(e:DragEvent){dragging.value=false; receive(e.dataTransfer?.files ?? null)}
function goPrepare(index:number){state.activeIndex=index; step.value=2}
function selectStep(next:number){ if(next===1 || state.photos.length) step.value=next }
function printPages(){ window.print() }
</script>
<template><q-layout view="hHh lpR fFf"><AppHeader/><q-page-container><main><WorkflowSteps :step="step" @select="selectStep"/>
  <section v-if="step===1" class="panel intro-panel"><div class="intro-copy"><div class="eyebrow">Your print studio</div><h1>Turn a folder of memories<br/><em>into fewer sheets.</em></h1><p>Add all your photos at once. Paperfit prepares each crop and finds a space-saving layout for standard A4 paper.</p><q-btn unelevated color="primary" icon="add_photo_alternate" label="Choose photos" size="lg" @click="input?.click()"/><span class="format-note">JPG, PNG, WEBP and HEIC*</span></div><div class="drop-zone" :class="{dragging}" @dragover.prevent="dragging=true" @dragleave="dragging=false" @drop.prevent="drop"><div class="floating-photo one"></div><div class="floating-photo two"></div><div class="floating-photo three"></div><q-icon name="file_upload"/><strong>Drop your photos here</strong><span>or click “Choose photos”</span></div></section>
  <section v-else-if="step===2" class="workspace"><div class="workspace-head"><div><div class="eyebrow">Step 2 · Prepare</div><h2>Crop & size your photos</h2><p>Review each photo and pick its final print size.</p></div><div class="progress-pill">{{state.activeIndex+1}} of {{state.photos.length}}</div></div><div class="editor-grid"><aside class="photo-rail"><button v-for="(photo,i) in state.photos" :key="photo.id" :class="{active:i===state.activeIndex}" @click="state.activeIndex=i"><img :src="photo.url"/><span>{{i+1}}</span><q-icon v-if="i < state.activeIndex" name="check_circle"/></button><button class="rail-add" @click="input?.click()"><q-icon name="add"/></button></aside><div class="editor-card"><PhotoCropper/></div><aside class="settings-card" v-if="activePhoto"><div class="section-label">Photo details</div><h3>{{activePhoto.name}}</h3><span class="pixel-size">{{activePhoto.naturalWidth}} × {{activePhoto.naturalHeight}} px</span><div class="section-label top-gap">Print size</div><label v-for="t in state.templates" :key="t.id" class="size-option" :class="{selected:activePhoto.templateId===t.id}"><input type="radio" v-model="activePhoto.templateId" :value="t.id"/><i :style="{background:t.color}"></i><span><b>{{t.name}}</b><small>{{t.width}} × {{t.height}} mm</small></span><q-icon name="check_circle"/></label><q-separator/><q-btn flat color="negative" icon="delete_outline" label="Remove photo" @click="removePhoto(activePhoto.id)"/></aside></div><TemplateManager/><div class="action-bar"><q-btn flat icon="arrow_back" label="Back" @click="step=1"/><div><q-btn flat label="Previous" :disable="state.activeIndex===0" @click="state.activeIndex--"/><q-btn v-if="state.activeIndex<state.photos.length-1" unelevated color="primary" icon-right="arrow_forward" label="Next photo" @click="state.activeIndex++"/><q-btn v-else unelevated color="primary" icon-right="auto_awesome_mosaic" label="Arrange pages" @click="step=3"/></div></div></section>
  <section v-else class="workspace arrange"><div class="workspace-head"><div><div class="eyebrow">Step 3 · Arrange & print</div><h2>Your most efficient layout</h2><p>{{state.photos.length}} photos fitted onto {{pages.length}} A4 {{pages.length===1?'sheet':'sheets'}}.</p></div><div class="saving-badge"><q-icon name="eco"/><span><b>{{pages.length}} sheet{{pages.length===1?'':'s'}}</b> ready to print</span></div></div><div class="layout-controls"><label>Page margin <b>{{state.margin}} mm</b><q-slider v-model="state.margin" :min="0" :max="20"/></label><label>Photo spacing <b>{{state.gap}} mm</b><q-slider v-model="state.gap" :min="0" :max="10"/></label><q-space/><q-btn outline icon="edit" label="Edit photos" @click="step=2"/><q-btn unelevated color="primary" icon="print" label="Print sheets" @click="printPages"/></div><div class="pages-grid"><A4Page v-for="(page,i) in pages" :key="i" :page="page" :number="i+1"/></div></section>
  <input ref="input" hidden multiple type="file" accept="image/*" @change="receive(($event.target as HTMLInputElement).files)"/><q-inner-loading :showing="loading"><q-spinner color="primary" size="48px"/></q-inner-loading>
</main></q-page-container></q-layout></template>
