<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import AppHeader from './components/AppHeader.vue'
import PhotoCropper from './components/PhotoCropper.vue'
import A4Page from './components/A4Page.vue'
import { activePhoto, importFiles, persistProject, removePhoto, resetProject, restoreProject, state } from './store/photoStore'
import { packPhotos } from './utils/packing'
import { loadStep, saveStep } from './utils/persistence'
import { snapPhotoToTemplate } from './utils/cropping'
import { calculatedPrintSize, dpiQuality, effectiveDpi } from './utils/printSizing'
const step = ref(loadStep()), input = ref<HTMLInputElement>(), loading = ref(false), initialized = ref(false), showBackWarning = ref(false), showArrangeWarning = ref(false), showLayoutEditor = ref(false), showBulkPrepare = ref(false), showDpiHelp = ref(false), showShortcuts = ref(false)
const bulkScope = ref<'all' | 'unvalidated' | 'from-current'>('unvalidated')
const bulkTemplateId = ref('small'), bulkSnap = ref(true), bulkValidate = ref(false)
const bulkUndo = ref<{ activeIndex: number; photos: { id: string; templateId: string; cropValidated: boolean; crop: { left: number; top: number; right: number; bottom: number } }[] }>()
const pages = computed(() => packPhotos(state.photos, state.templates))
const unvalidatedCount = computed(() => state.photos.filter(photo => !photo.cropValidated).length)
const validatedCount = computed(() => state.photos.length - unvalidatedCount.value)
const activeTemplate = computed(() => state.templates.find(template => template.id === activePhoto.value?.templateId))
const activeDpi = computed(() => activePhoto.value && activeTemplate.value ? effectiveDpi(activePhoto.value, activeTemplate.value) : 0)
const activeDpiQuality = computed(() => dpiQuality(activeDpi.value))
const activePrintSize = computed(() => activePhoto.value && activeTemplate.value ? calculatedPrintSize(activePhoto.value, activeTemplate.value) : undefined)
const bulkTargets = computed(() => state.photos.filter((photo, index) => bulkScope.value === 'all' || (bulkScope.value === 'unvalidated' && !photo.cropValidated) || (bulkScope.value === 'from-current' && index >= state.activeIndex)))
async function receive(files: FileList | null) { if (!files?.length) return; loading.value = true; try { await importFiles([...files]); if (state.photos.length) step.value = 2 } finally { loading.value = false; if (input.value) input.value.value = '' } }
function printPages() { window.print() }
function setActiveTemplate(templateId: string) { if (!activePhoto.value) return; activePhoto.value.templateId = templateId; activePhoto.value.cropValidated = false }
function validateActiveCrop() { if (!activePhoto.value) return; activePhoto.value.cropValidated = true; if (state.activeIndex < state.photos.length - 1) state.activeIndex++ }
function requestArrange() { if (unvalidatedCount.value) showArrangeWarning.value = true; else step.value = 3 }
function reviewUnvalidated() { const index = state.photos.findIndex(photo => !photo.cropValidated); if (index >= 0) state.activeIndex = index; showArrangeWarning.value = false }
function arrangeAnyway() { showArrangeWarning.value = false; step.value = 3 }
function editFromLayout(photoId: string) { const index = state.photos.findIndex(photo => photo.id === photoId); if (index < 0) return; state.activeIndex = index; showLayoutEditor.value = true }
function validateLayoutEdit() { if (activePhoto.value) activePhoto.value.cropValidated = true; showLayoutEditor.value = false }
function applyBulkPrepare() {
  const targets = bulkTargets.value
  const template = state.templates.find(item => item.id === bulkTemplateId.value)
  if (!targets.length || !template) return
  bulkUndo.value = { activeIndex: state.activeIndex, photos: targets.map(photo => ({ id: photo.id, templateId: photo.templateId, cropValidated: photo.cropValidated, crop: { ...photo.crop } })) }
  for (const photo of targets) {
    photo.templateId = template.id
    if (bulkSnap.value) snapPhotoToTemplate(photo, template)
    else photo.cropValidated = false
    if (bulkValidate.value) photo.cropValidated = true
  }
  const firstIndex = state.photos.findIndex(photo => photo.id === targets[0].id)
  if (firstIndex >= 0) state.activeIndex = firstIndex
  showBulkPrepare.value = false
}
function undoBulkPrepare() {
  const undo = bulkUndo.value
  if (!undo) return
  for (const previous of undo.photos) {
    const photo = state.photos.find(item => item.id === previous.id)
    if (photo) { photo.templateId = previous.templateId; photo.cropValidated = previous.cropValidated; photo.crop = { ...previous.crop } }
  }
  state.activeIndex = Math.min(undo.activeIndex, Math.max(0, state.photos.length - 1))
  bulkUndo.value = undefined
}
function jumpToFirstUnvalidated() { const index = state.photos.findIndex(photo => !photo.cropValidated); if (index >= 0) state.activeIndex = index }
function qualityForPhoto(photo: typeof state.photos[number]) { const template = state.templates.find(item => item.id === photo.templateId); const dpi = template ? effectiveDpi(photo, template) : 0; return { dpi, ...dpiQuality(dpi) } }
function resetActiveCrop() { if (!activePhoto.value) return; activePhoto.value.crop = { left: 0, top: 0, right: 100, bottom: 100 }; activePhoto.value.cropValidated = false }
function snapActiveCrop() { if (activePhoto.value && activeTemplate.value) snapPhotoToTemplate(activePhoto.value, activeTemplate.value) }
function handleShortcut(event: KeyboardEvent) {
  const target = event.target as HTMLElement | null
  if (step.value !== 2 || showBackWarning.value || showArrangeWarning.value || showBulkPrepare.value || showDpiHelp.value || showShortcuts.value || target?.matches('input, textarea, select')) return
  if (event.key === 'Enter') { event.preventDefault(); validateActiveCrop() }
  else if (event.key === 'ArrowLeft' && state.activeIndex > 0) { event.preventDefault(); state.activeIndex-- }
  else if (event.key === 'ArrowRight' && state.activeIndex < state.photos.length - 1) { event.preventDefault(); state.activeIndex++ }
  else if (['1', '2', '3'].includes(event.key)) { event.preventDefault(); setActiveTemplate(['small', 'medium', 'big'][Number(event.key) - 1]) }
  else if (event.key.toLowerCase() === 's') { event.preventDefault(); snapActiveCrop() }
  else if (event.key.toLowerCase() === 'r') { event.preventDefault(); resetActiveCrop() }
}
async function confirmBack() { loading.value = true; try { await resetProject(); step.value = 1; showBackWarning.value = false } finally { loading.value = false } }
onMounted(async () => {
  try { await restoreProject(); if (!state.photos.length) step.value = 1 } finally { initialized.value = true }
  saveStep(step.value)
  let timer: number | undefined
  watch(state, () => { window.clearTimeout(timer); timer = window.setTimeout(persistProject, 150) }, { deep: true })
  watch(step, saveStep)
  window.addEventListener('beforeunload', () => { persistProject(); saveStep(step.value) })
  window.addEventListener('keydown', handleShortcut)
})
onBeforeUnmount(() => window.removeEventListener('keydown', handleShortcut))
</script>

<template>
  <q-layout view="hHh lpR fFf" class="bg-dark text-white"><AppHeader /><q-page-container><q-page :class="step === 2 ? 'q-pa-sm q-pa-md-md' : 'q-pa-md q-pa-lg-xl'">
    <section v-if="step === 1" class="full-width q-pa-lg q-pl-xl">
      <div class="text-overline text-primary">Photo print organizer</div><div class="text-h3 text-weight-bold q-mt-sm">Fit more photos on fewer A4 sheets</div><div class="text-body1 text-grey-4 q-mt-md" style="max-width: 680px">Add photos in bulk, choose their print sizes, crop them, and generate an efficient layout ready to print.</div><div class="q-mt-lg"><q-btn color="primary" text-color="black" icon="add_photo_alternate" label="Choose photos" size="lg" @click="input?.click()" /></div>
    </section>

    <section v-else-if="step === 2">
      <div class="row items-center justify-between q-mb-sm"><div><div class="text-overline text-primary">Prepare photos</div><div class="text-h4 text-weight-bold">Crop and choose a size</div></div><div class="row items-center q-gutter-sm"><q-btn flat round color="grey-4" icon="keyboard" @click="showShortcuts=true"><q-tooltip>Keyboard shortcuts</q-tooltip></q-btn><q-btn v-if="bulkUndo" outline color="primary" icon="undo" label="Undo bulk change" @click="undoBulkPrepare" /><q-btn color="primary" text-color="black" icon="auto_fix_high" label="Bulk prepare" @click="showBulkPrepare=true" /><q-badge color="primary" text-color="black" class="q-pa-sm">{{ state.activeIndex + 1 }} / {{ state.photos.length }}</q-badge></div></div>
      <q-card flat bordered class="bg-grey-10 text-white q-mb-md"><q-card-section class="row items-center q-gutter-sm q-py-xs"><q-chip square color="grey-9" text-color="white" icon="photo_library">{{ state.photos.length }} photos</q-chip><q-chip square color="positive" text-color="white" icon="check_circle">{{ validatedCount }} validated</q-chip><q-chip clickable square :color="unvalidatedCount ? 'warning' : 'grey-8'" :text-color="unvalidatedCount ? 'black' : 'white'" icon="pending_actions" @click="jumpToFirstUnvalidated">{{ unvalidatedCount }} remaining<q-tooltip v-if="unvalidatedCount">Jump to first unvalidated photo</q-tooltip></q-chip><q-chip square color="grey-9" text-color="white" icon="description">{{ pages.length }} estimated sheets</q-chip></q-card-section></q-card>
      <div class="row q-col-gutter-lg items-start">
        <aside class="col-12 col-md-3 col-lg-2"><q-card flat bordered class="bg-grey-10 text-white"><q-card-section class="row items-center justify-between"><div class="text-h6">Photos</div><q-btn flat round dense color="primary" icon="add_photo_alternate" @click="input?.click()" /></q-card-section><q-separator dark /><q-list separator class="photo-list"><q-item v-for="(photo, index) in state.photos" :key="photo.id" clickable :active="index === state.activeIndex" active-class="bg-grey-9 text-primary" @click="state.activeIndex=index"><q-item-section avatar><q-img :src="photo.url" width="52px" height="52px" fit="cover" /></q-item-section><q-item-section><q-item-label lines="1">{{ photo.name }}</q-item-label><q-item-label caption class="text-grey-5">Photo {{ index + 1 }}</q-item-label></q-item-section><q-item-section v-if="photo.cropValidated || qualityForPhoto(photo).dpi < 300" side><div class="row no-wrap q-gutter-xs"><q-icon v-if="qualityForPhoto(photo).dpi < 300" name="warning" :color="qualityForPhoto(photo).color" size="22px"><q-tooltip>{{ qualityForPhoto(photo).dpi }} DPI · {{ qualityForPhoto(photo).label }}</q-tooltip></q-icon><q-icon v-if="photo.cropValidated" name="check_circle" color="positive" size="24px"><q-tooltip>Crop validated</q-tooltip></q-icon></div></q-item-section></q-item></q-list></q-card></aside>
        <div class="col-12 col-md-6 col-lg-7"><q-card flat bordered class="bg-grey-10 text-white"><q-card-section><PhotoCropper /></q-card-section></q-card></div>
        <aside v-if="activePhoto" class="col-12 col-md-3"><q-card flat bordered class="bg-grey-10 text-white"><q-card-section><div class="text-overline text-primary">Photo details</div><div class="text-subtitle1 text-weight-bold ellipsis">{{ activePhoto.name }}</div><div class="text-caption text-grey-5">{{ activePhoto.naturalWidth }} × {{ activePhoto.naturalHeight }} px</div></q-card-section><q-separator dark /><q-card-section><div class="row items-center justify-between"><div class="text-subtitle2">Print quality</div><q-btn flat round dense size="sm" color="grey-4" icon="info_outline" @click="showDpiHelp=true" /></div><q-badge :color="activeDpiQuality.color" :text-color="activeDpiQuality.color === 'warning' ? 'black' : 'white'" class="q-pa-sm q-mt-sm">{{ activeDpi }} DPI · {{ activeDpiQuality.label }}</q-badge><div v-if="activePrintSize" class="text-caption text-grey-5 q-mt-sm">Estimated print: {{ activePrintSize.width.toFixed(0) }} × {{ activePrintSize.height.toFixed(0) }} mm</div></q-card-section><q-separator dark /><q-card-section><div class="text-subtitle2 q-mb-sm">Photo size</div><div class="text-caption text-grey-5 q-mb-sm">The crop always keeps its proportions. These dimensions are approximate unless you use “Snap to optimized ratio”.</div><q-option-group :model-value="activePhoto.templateId" :options="state.templates.map(t => ({ label: `${t.name} — ${t.width} × ${t.height} mm`, value: t.id }))" color="primary" type="radio" @update:model-value="setActiveTemplate" /></q-card-section><q-separator dark /><q-card-section><q-btn v-if="!activePhoto.cropValidated" class="full-width" color="positive" text-color="white" icon="check_circle" label="Validate crop" @click="validateActiveCrop" /><q-btn v-else class="full-width" outline color="positive" icon="check_circle" label="Crop validated" @click="activePhoto.cropValidated=false"><q-tooltip>Click to mark this crop as needing review</q-tooltip></q-btn></q-card-section><q-card-actions><q-btn flat color="negative" icon="delete_outline" label="Remove photo" @click="removePhoto(activePhoto.id)" /></q-card-actions></q-card></aside>
      </div>
      <div class="row justify-between items-center q-mt-md"><q-btn flat color="grey-4" icon="arrow_back" label="Back" @click="showBackWarning=true" /><div class="q-gutter-sm"><q-btn flat color="grey-4" label="Previous" :disable="state.activeIndex===0" @click="state.activeIndex--" /><q-btn color="primary" text-color="black" icon-right="arrow_forward" label="Next photo" :disable="state.activeIndex >= state.photos.length-1" @click="state.activeIndex++" /><q-btn color="primary" text-color="black" icon="auto_awesome_mosaic" label="Arrange pages" @click="requestArrange" /></div></div>
    </section>

    <section v-else>
      <div class="print-toolbar row items-center justify-between q-mb-lg"><div><div class="text-overline text-primary">Arrange and print</div><div class="text-h4 text-weight-bold">A4 layout</div><div class="text-body2 text-grey-4 q-mt-xs">{{ state.photos.length }} photos on {{ pages.length }} sheet{{ pages.length === 1 ? '' : 's' }}</div></div><div class="q-gutter-sm"><q-btn outline color="primary" icon="edit" label="Edit photos" @click="step=2" /><q-btn color="primary" text-color="black" icon="print" label="Print sheets" @click="printPages" /></div></div>
      <div class="print-pages row q-col-gutter-xl justify-center"><div v-for="(page,index) in pages" :key="index" class="print-page-column col-12 col-sm-6 col-lg-4"><A4Page :page="page" :number="index+1" @photo-click="editFromLayout($event.id)" /></div></div>
    </section>
    <input ref="input" hidden multiple type="file" accept="image/*" @change="receive(($event.target as HTMLInputElement).files)" /><q-inner-loading :showing="loading || !initialized" dark><q-spinner color="primary" size="48px" /></q-inner-loading>
    <q-dialog v-model="showBackWarning" persistent><q-card class="bg-grey-10 text-white" style="width: 460px; max-width: 94vw"><q-card-section class="row items-center q-gutter-md"><q-icon name="warning" color="negative" size="36px" /><div><div class="text-h6">Erase this project?</div><div class="text-body2 text-grey-4">Going back will remove every imported photo, crop, size choice, and validation.</div></div></q-card-section><q-card-actions align="right"><q-btn flat color="grey-4" label="Keep working" v-close-popup /><q-btn color="negative" icon="delete_forever" label="Erase and go back" @click="confirmBack" /></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="showArrangeWarning" persistent><q-card class="bg-grey-10 text-white" style="width: 480px; max-width: 94vw"><q-card-section class="row items-center q-gutter-md"><q-icon name="warning" color="primary" size="36px" /><div><div class="text-h6">Some crops are not validated</div><div class="text-body2 text-grey-4">{{ unvalidatedCount }} photo{{ unvalidatedCount === 1 ? '' : 's' }} still need{{ unvalidatedCount === 1 ? 's' : '' }} review. You can arrange them using their current crops or return to finish reviewing.</div></div></q-card-section><q-card-actions align="right"><q-btn flat color="grey-4" label="Review photos" @click="reviewUnvalidated" /><q-btn color="primary" text-color="black" icon="auto_awesome_mosaic" label="Arrange anyway" @click="arrangeAnyway" /></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="showBulkPrepare" persistent><q-card class="bg-grey-10 text-white" style="width: 560px; max-width: 94vw"><q-card-section><div class="text-h6">Bulk prepare photos</div><div class="text-body2 text-grey-4">Apply the same size and crop behavior to many photos at once.</div></q-card-section><q-separator dark /><q-card-section class="q-gutter-lg"><div><div class="text-subtitle2 q-mb-sm">Which photos?</div><q-option-group v-model="bulkScope" :options="[{label:'All photos',value:'all'},{label:'Unvalidated photos only',value:'unvalidated'},{label:'Current photo onward',value:'from-current'}]" color="primary" type="radio" /></div><q-select v-model="bulkTemplateId" dark outlined emit-value map-options label="Photo size" :options="state.templates.map(t => ({ label: `${t.name} — ${t.width} × ${t.height} mm`, value: t.id }))" /><div><q-toggle v-model="bulkSnap" color="primary" label="Snap each photo to its largest optimized crop" /><div class="text-caption text-grey-5 q-ml-xl">This centers every crop. Review afterward to reposition important subjects.</div></div><div><q-toggle v-model="bulkValidate" color="primary" label="Mark affected photos as validated" /><div class="text-caption text-grey-5 q-ml-xl">Leave this off if you want to review each composition.</div></div><q-banner class="bg-grey-9 text-white rounded-borders"><template #avatar><q-icon name="auto_fix_high" color="primary" /></template><b>{{ bulkTargets.length }} photo{{ bulkTargets.length === 1 ? '' : 's' }}</b> will use {{ state.templates.find(t => t.id === bulkTemplateId)?.name }}.<div class="text-caption text-grey-4">{{ bulkSnap ? 'Optimized crop will be applied.' : 'Existing crop will be kept.' }} {{ bulkValidate ? 'Photos will be validated.' : 'Photos will remain ready for review.' }}</div></q-banner></q-card-section><q-card-actions align="right"><q-btn flat color="grey-4" label="Cancel" v-close-popup /><q-btn color="primary" text-color="black" icon="done_all" label="Apply bulk changes" :disable="bulkTargets.length === 0" @click="applyBulkPrepare" /></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="showDpiHelp"><q-card class="bg-grey-10 text-white" style="width: 520px; max-width: 94vw"><q-card-section><div class="text-h6">Understanding print quality</div><div class="text-body2 text-grey-4 q-mt-sm">DPI means image pixels per printed inch. It is calculated from the pixels remaining after crop and the photo’s estimated physical print size.</div></q-card-section><q-card-section class="q-gutter-md"><q-banner class="bg-green-10 rounded-borders"><b>300 DPI or more · Excellent</b><div class="text-caption">Sharp photo-quality output, including when viewed closely.</div></q-banner><q-banner class="bg-orange-10 rounded-borders"><b>150–299 DPI · Acceptable</b><div class="text-caption">Usually suitable for an album, but fine details may be softer.</div></q-banner><q-banner class="bg-red-10 rounded-borders"><b>Below 150 DPI · Low resolution</b><div class="text-caption">The printed photo may look blurry or pixelated. Use a smaller size or retain more of the original crop.</div></q-banner><div class="text-caption text-grey-5">DPI is an estimate. Printer, paper, compression, and viewing distance also affect the final result.</div></q-card-section><q-card-actions align="right"><q-btn color="primary" text-color="black" label="Got it" v-close-popup /></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="showShortcuts"><q-card class="bg-grey-10 text-white" style="width: 480px; max-width: 94vw"><q-card-section><div class="text-h6">Keyboard shortcuts</div><div class="text-body2 text-grey-4">Use these while preparing photos.</div></q-card-section><q-list separator><q-item><q-item-section><q-item-label>Validate crop and continue</q-item-label></q-item-section><q-item-section side><q-badge color="grey-8">Enter</q-badge></q-item-section></q-item><q-item><q-item-section><q-item-label>Previous / next photo</q-item-label></q-item-section><q-item-section side><q-badge color="grey-8">← / →</q-badge></q-item-section></q-item><q-item><q-item-section><q-item-label>Phone / Medium / Big</q-item-label></q-item-section><q-item-section side><q-badge color="grey-8">1 / 2 / 3</q-badge></q-item-section></q-item><q-item><q-item-section><q-item-label>Snap to optimized ratio</q-item-label></q-item-section><q-item-section side><q-badge color="grey-8">S</q-badge></q-item-section></q-item><q-item><q-item-section><q-item-label>Reset crop</q-item-label></q-item-section><q-item-section side><q-badge color="grey-8">R</q-badge></q-item-section></q-item></q-list><q-card-actions align="right"><q-btn color="primary" text-color="black" label="Close" v-close-popup /></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="showLayoutEditor" persistent maximized transition-show="slide-up" transition-hide="slide-down"><q-card class="bg-dark text-white"><q-toolbar class="bg-grey-10"><q-icon name="crop" color="primary" size="28px" class="q-mr-md" /><q-toolbar-title>Edit photo</q-toolbar-title><q-btn flat round dense icon="close" @click="showLayoutEditor=false" /></q-toolbar><q-card-section v-if="activePhoto" class="row q-col-gutter-xl q-pa-lg"><div class="col-12 col-md-9"><q-card flat bordered class="bg-grey-10 text-white"><q-card-section><PhotoCropper /></q-card-section></q-card></div><div class="col-12 col-md-3"><q-card flat bordered class="bg-grey-10 text-white"><q-card-section><div class="text-overline text-primary">Photo size</div><div class="text-subtitle1 ellipsis q-mb-sm">{{ activePhoto.name }}</div><div class="text-caption text-grey-5 q-mb-md">Dimensions are approximate unless you use “Snap to optimized ratio”.</div><q-option-group :model-value="activePhoto.templateId" :options="state.templates.map(t => ({ label: `${t.name} — ${t.width} × ${t.height} mm`, value: t.id }))" color="primary" type="radio" @update:model-value="setActiveTemplate" /></q-card-section><q-separator dark /><q-card-actions vertical><q-btn class="full-width" color="positive" icon="check_circle" label="Validate and close" @click="validateLayoutEdit" /><q-btn flat class="full-width" color="grey-4" label="Close" @click="showLayoutEditor=false" /></q-card-actions></q-card></div></q-card-section></q-card></q-dialog>
  </q-page></q-page-container></q-layout>
</template>
